#:schema node_modules/wrangler/config-schema.json
name = "salone-oppo-hub"
main = ".open-next/worker.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]
minify = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Cron Triggers - scrape opportunities every 15 minutes
[triggers]
crons = ["*/15 * * * *"]
