#:schema node_modules/wrangler/config-schema.json
name = "salone-oppo-hub"
main = ".open-next/worker.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]
minify = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Cron triggers disabled - sufficient data collected
# [triggers]
# crons = ["*/15 * * * *"]
